#!/bin/bash
# Instalar y registrar el kernel de R
R -e "IRkernel::installspec(user = FALSE)"

# Instalar el kernel de Python (opcional)
python -m ipykernel install --sys-prefix

# Instalar paquetes de Python faltantes
pip install --no-cache-dir pyleoclim

# Imprimir un mensaje indicando que el entorno está listo
echo "Binder environment is ready!"

